export default [
  {
    id: 1,
    name: 'Lanchonete Raio de Luz',
    rate: 6,
    image: require('../../../assets/images/mocks/raio_de_luz.jpg'),
    openingTime: 17,
    closingTime: 22,
    freightValue: 5.5,
  },
  {
    id: 2,
    name: 'Pizzaria Roma',
    rate: 6,
    image: require('../../../assets/images/mocks/raio_de_luz.jpg'),
    openingTime: 17,
    closingTime: 22,
    freightValue: 5.5,
  },
  {
    id: 3,
    name: 'Lanchonete Raio de Luz',
    rate: 6,
    image: require('../../../assets/images/mocks/raio_de_luz.jpg'),
    openingTime: 17,
    closingTime: 22,
    freightValue: 5.5,
  },
  {
    id: 4,
    name: 'Lanchonete Raio de Luz',
    rate: 6,
    image: require('../../../assets/images/mocks/raio_de_luz.jpg'),
    openingTime: 17,
    closingTime: 22,
    freightValue: 5.5,
  },
  {
    id: 6,
    name: 'Lanchonete Raio de Luz',
    rate: 6,
    image: require('../../../assets/images/mocks/raio_de_luz.jpg'),
    openingTime: 17,
    closingTime: 22,
    freightValue: 5.5,
  },
];
